### ISSUE TITLE
Content usage wrapper

### ISSUE THREAD

**Issue by jonkeane** [posit-dev/posit-sdk-py#137]
It would be nice to have a wrapper that lets me get content usage _regardless of the content is Shiny or not_. Currently we have [`/v1/instrumentation/shiny/usage`](https://docs.posit.co/connect/api/#get-/v1/instrumentation/shiny/usage) for shiny usage and [`/v1/instrumentation/content/visits`](https://docs.posit.co/connect/api/#get-/v1/instrumentation/content/visits) for everything else. They contain much of the same information (though there isn't complete overlap!), but it looks like enough that we could return a combined list that has the fields when they are relevant and either doesn't have them or they are marked as `NULL` when they are not relevant.

See: https://github.com/rstudio/connectapi/issues/218

**Comment by nealrichardson** [comment]
I believe this will involve https://github.com/posit-dev/posit-sdk-py/issues/75.
