### ISSUE TITLE
Does `Config` need to exist at all?

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/posit-sdk-py#139]
Reflecting on https://github.com/posit-dev/posit-sdk-py/pull/124, where we now pass `Config` to all `Resources`. `Config` just holds `url` and `api_key`, but we never access `api_key` anywhere. The only time we access `api_key` is in the `Auth` constructor, which only uses `api_key` and not `url`. 

My first thought was that we should only be passing `url` around to the `Resources`, no need to keep the API key so visible in each object. But then I wondered if we should just eliminate the object entirely.

**Comment by tdstein** [comment]
I'm surprised we haven't needed to add any additional properties. But if additional system properties are needed, I would place them here.

Here's some other information that might need to go there in the future:

- User-Agent
- HTTP Timeout
- Proxy configuration?
- SSL certificate information?
- Additional OS information
- Logging / Verbosity settings
