### ISSUE TITLE
Better docstrings for content.update

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/posit-sdk-py#140]
They're all pretty tautological, just restating the field name. 

```
            name (str): The name of the content.
            title (Optional[str]): The title of the content.
            description (str): The description of the content.
            access_type (str): The access type of the content.
...
```

There's more useful information in the [API docs](https://docs.posit.co/connect/api/#patch-/v1/content/-guid-), explaining what things are for, what valid values are, etc. We should grab those from the swagger spec and put them in there, translating to python as appropriate. 

Probably also would be good to include xrefs to the hosted connect API docs for the relevant APIs.

**Comment by tdstein** [comment]
I've been going back and forth on whether to link directly to the API documentation. It's possible for the hosted documentation to diverge from the docstrings over time.

**Comment by tdstein** [comment]
Related to #135
