### ISSUE TITLE
CRUD for content environment variables

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/posit-sdk-py#143]

**Comment by kellobri** [comment]
User Research Anecdote: Folks on the Posit Data Science team are loving the `updateServerEnvVars()` function in rsconnect added in 2023

> rsconnect gains two new functions for understanding and updating the environment variables that your apps currently use. listServerEnvVars() will return a data frame of applications, with a envVars list-column giving the names of the environment variables used by each application. updateServerEnvVars() will update all applications that use a specific environment variable with the current value of that environment variable

**Comment by tdstein** [comment]
Resolved by #236
