### ISSUE TITLE
Add `owner` details to the output of `connect.content.find()`

### ISSUE THREAD

**Issue by gsingh91** [posit-dev/posit-sdk-py#158]
for consistency with R `connectapi` package, the output of `connect.content.find()` should include an owner column with details of the content item owner(`owner$guid`, `owner$first_name`, `owner$last_name` and `owner$username`). 
This would enable any audit functionality we are building in the cookbooks as we would be able to get both content and owner details in one function(something which can already be done in R).

**Comment by tdstein** [comment]
@gsingh91 - Thanks for the feature request.  Would the following behavior suffice?

```py
for item in connect.content.find():
    owner = item.owner
    print(owner.guid, owner.first_name, owner.last_name, owner.username)
```

**Comment by gsingh91** [comment]
yes, as long as owner is available in the output of the API call, it should be fine. thanks

**Comment by gsingh91** [comment]
@tdstein I think it would be better to include `owner` in the API call at the `content` level, as is done in `connectapi` or at least have an argument to include it in content. This way, API call per item wont be needed and it would speed up the process. Otherwise in the current implementation, this process would be really slow for a large Connect instance in a customer environment with possibly hundreds of items.

**Comment by gsingh91** [comment]
Ref: https://github.com/posit-dev/connect-cookbook/pull/7#discussion_r1554268858

**Comment by tdstein** [comment]
Ok, made the update to improve performance. See

`pip install git+https://github.com/posit-dev/posit-sdk-py.git@3e34626473f575ee3cbcd469c2614e70db3914fb`

```
from posit.connect import Client

c = Client()

for item in c.content.find():
    print(item.owner)

**Comment by gsingh91** [comment]
Thanks @tdstein ! I am able to get the information I need for the cookbook now.
