### ISSUE TITLE
Download a deployment bundle

### ISSUE THREAD

**Issue by brooklynbagel** [posit-dev/posit-sdk-py#191]
See https://docs.posit.co/connect/api/#get-/v1/content/-guid-/bundles/-id-/download and https://pkgs.rstudio.com/connectapi/reference/download_bundle.html

- Since the API endpoint marked as experimental, there should be some sort of message or warning?
-  The `tar` archive could be either saved to disk or loaded into memory. For an in-memory bundle, I'm current some code that looks like this:

    ```python
    import io
    import tarfile
    ...
    r = client.get(f"/v1/content/{content_guid}/bundles/{bundle_id}/download")
    bundle = tarfile.open(fileobj=io.BytesIO(r.content))
    ```
- Not sure what the API should look like especially if this will support __both__ saving to disk and just loading in-memory.
- Should this then come with all the methods for bundles? See [list bundles](https://docs.posit.co/connect/api/#get-/v1/content/-guid-/bundles), [create a bundle by uploading an archive](https://docs.posit.co/connect/api/#post-/v1/content/-guid-/bundles), [get bundle details](https://docs.posit.co/connect/api/#get-/v1/content/-guid-/bundles/-id-) and [delete a bundle](https://docs.posit.co/connect/api/#delete-/v1/content/-guid-/bundles/-id-).

**Comment by nealrichardson** [comment]
I believe this is already implemented, no? https://github.com/posit-dev/posit-sdk-py/blob/main/src/posit/connect/bundles.py#L122

> Since the API endpoint marked as experimental, there should be some sort of message or warning?

It's a proper v1 endpoint, not experimental. That said, we're not going to add scary warnings in the SDK for any future experimental features, nor for APIs that have existed for years but just weren't documented properly. For historical reasons, `connectapi` raised lots of warnings like that, and we're going to fix that too.

**Comment by brooklynbagel** [comment]
Sorry, I missed this was added from an earlier version of the SDK I was using. I also updated the link (I originally linked to the experimental API) without updating the issue.
