### ISSUE TITLE
Implement Content Git Repository API

### ISSUE THREAD

**Issue by kmasiello** [posit-dev/posit-sdk-py#192]
Implement GET and PUT wrappers to view and modify the git repository settings for content.

Will greatly improve recipe at https://github.com/posit-dev/connect-cookbook/pull/57

*API Proposal*

```py
from posit import connect

client = connect.Client()
content = client.content.get(...)
repository = content.repository or content.create_repository(...) # GET or POST
repository.update(...) # PATCH
repository.delete() # DELETE
```

**Comment by zackverham** [comment]
@tdstein I can try to pick this one up as sand work!
