### ISSUE TITLE
Add Python dependency interrogation technique

### ISSUE THREAD

**Issue by tdstein** [posit-dev/posit-sdk-py#230]
Implement a strategy to interrogate the requirements.txt file for bundles that have one. Some initial thoughts:

- Create an abstraction on the archive written by `bundle. download`.
- Add a method to that abstraction that allows the user to inspect the requirements.txt file.

```python
archive = bundle.download('archive.tar.gz')
'dash' in archive.requirements_txt
>>> True
```

**Comment by tdstein** [comment]
Relates to #304

**Comment by jonkeane** [comment]
This might even be superseded by #304 yeah?

**Comment by tdstein** [comment]
Most likely, yes. Depends on what we want to do with backwards compatibility with prior Connect versions.

**Comment by jonkeane** [comment]
And, depending on the shape of the API, we might have different information from requirements.txt that is relevant

**Comment by tdstein** [comment]
Closing as not planned since the functionality was added in https://github.com/posit-dev/posit-sdk-py/issues/304
