### ISSUE TITLE
Error handler should expose the `payload` field of ApiErrors returned by Connect

### ISSUE THREAD

**Issue by dbkegley** [posit-dev/posit-sdk-py#234]
Some error messages returned by Connect use the `payload` field to provide extra context. We should emit this field if it is provided.

Specifically some of our OAuth integration code uses the payload field to expose the `ErrorDescription` returned when OAuth client errors occur. 

https://github.com/rstudio/connect/blob/fd54c65c7b5779550034da495871bf2a138f93dd/src/connect/auth/oauth2/oauth2.go#L93-L101

The error code's generic message is overwritten by the `error` field of the response from the authorization server (`unauthorized_client`), and the `error_description` (`Invalid client or Invalid client credentials`) is stored in the `payload` field. 

```
ApiErrorOAuthAccessTokenRefreshFailure:     {http.StatusBadRequest, "Failed to refresh OAuth Access Token."},
```

![image](https://github.com/user-attachments/assets/a0bfefbb-c950-4504-89f3-2f12ae800684)

In this case, the actual response is: `{"code":219,"error":"unauthorized_client","payload":"Invalid client or Invalid client credentials"}`

**Comment by tdstein** [comment]
Resolved by #242
