### ISSUE TITLE
Add API Reference Documentation using Quartodoc

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/posit-sdk-py#29]
See https://machow.github.io/quartodoc/get-started/overview.html

**Comment by nealrichardson** [comment]
#157 is a start. We probably also want to add CI/CD and host multiple versions of the docs.

**Comment by nealrichardson** [comment]
@tdstein are we calling this done now?

**Comment by tdstein** [comment]
Yes - the initial work is done!
