### ISSUE TITLE
feat: Use the requests Session interface for runtime assertions

### ISSUE THREAD

**Issue by schloerke** [posit-dev/posit-sdk-py#325]
I think it would be wise to lean on the Python requests Session interface. Which does runtime assertions to verify the types. Our testing strategy will reveal any issues related to the incorrect type being used.

_Originally posted by @tdstein in https://github.com/posit-dev/posit-sdk-py/pull/300#discussion_r1833127353_

**Comment by tdstein** [comment]
@schloerke - should we close this as not planned?
