### ISSUE TITLE
Allow CI to run successfully on forks

### ISSUE THREAD

**Issue by nealrichardson** [posit-dev/posit-sdk-py#87]
Either skip the coverage step (I'd rather not) or see if the action can be made to work. https://github.com/orgoro/coverage/issues/259 has a few different approaches.

**Comment by tdstein** [comment]
I attempted various solutions to run successfully on forks but was unsuccessful. Therefore, I decided to disable the coverage report on forks for now. If https://github.com/orgoro/coverage/issues/259 is merged, we can update to use the proposed workflow.
