### ISSUE TITLE
Add a way to remove all viewers and collaborators from a piece of content

### ISSUE THREAD

**Issue by jonkeane** [posit-dev/posit-sdk-py#93]
Some folks would like a quick and easy way to revoke access to a piece of content. This can be accomplished today with the API one by one (though not yet with the SDK IIUC). But it would be nice to make a wrapper that encapsulates this functionality so someone can remove all of the users + viewers with one SDK call. We might add an API for this bulk action, but we can implement this SDK side before and see if it works for folks.

A possible sketch (though not a mandate):
```
from posit.connect import Client

con = Client()
content_to_clean = con.content.get(id = "...")
content_to_clean.remove_shares(viewers = True, collaborators = True) # I'm assuming these would actually both be True by default, but for clarity have them listed here.
```

We've had requests for this [in the Connect UI as well](https://github.com/rstudio/connect/issues/26151)

**Comment by nealrichardson** [comment]
Following #101, this would be something like:

```
for perm in con.content.get(id).permissions.find():
    if perm.role == "viewer":
        perm.delete()
```

You could wrap that in a function, but it might also be better suited as a cookbook recipe.

**Comment by tdstein** [comment]
@jonkeane - this is now possible via the snippet @nealrichardson provided above.

**Comment by nealrichardson** [comment]
I filed https://github.com/posit-dev/connect-cookbook/issues/5 in case we want to make a recipe for that.
